### PR TITLE
Move more blocking json serialization away from event loop

### LINKED ISSUE #591: KafkaProducerRecordBuilder is blocking EventLoop with JSON serialization
(*internal handle for resource planning: SDCISA-16204*)

```
2024-06-07T14:49:05,042 snapshot houston WARN BlockedThreadChecker - Thread Thread[vert.x-eventloop-thread-3,5,main] has been blocked for 89 ms
io.vertx.core.VertxException: Thread blocked
        at jdk.internal.math.FloatingDecimal.parseDouble(FloatingDecimal.java:110) ~[?:?]
        at java.lang.Double.parseDouble(Double.java:543) ~[?:?]
        at com.fasterxml.jackson.core.io.NumberInput.parseDouble(NumberInput.java:310) ~[jackson-core-2.13.0.jar:2.13.0]
        at com.fasterxml.jackson.core.util.TextBuffer.contentsAsDouble(TextBuffer.java:517) ~[jackson-core-2.13.0.jar:2.13.0]
        at com.fasterxml.jackson.core.base.ParserBase._parseSlowFloat(ParserBase.java:879) ~[jackson-core-2.13.0.jar:2.13.0]
        at com.fasterxml.jackson.core.base.ParserBase._parseNumericValue(ParserBase.java:832) ~[jackson-core-2.13.0.jar:2.13.0]
        at com.fasterxml.jackson.core.base.ParserBase.getNumberValue(ParserBase.java:597) ~[jackson-core-2.13.0.jar:2.13.0]
        at com.fasterxml.jackson.databind.deser.std.UntypedObjectDeserializer$Vanilla.deserialize(UntypedObjectDeserializer.java:737) ~[jackson-databind-2.13.0.jar:2.13.0]
        at com.fasterxml.jackson.databind.deser.std.UntypedObjectDeserializer$Vanilla.mapObject(UntypedObjectDeserializer.java:924) ~[jackson-databind-2.13.0.jar:2.13.0]
        at com.fasterxml.jackson.databind.deser.std.UntypedObjectDeserializer$Vanilla.deserialize(UntypedObjectDeserializer.java:707) ~[jackson-databind-2.13.0.jar:2.13.0]
        at com.fasterxml.jackson.databind.deser.std.UntypedObjectDeserializer$Vanilla.mapObject(UntypedObjectDeserializer.java:933) ~[jackson-databind-2.13.0.jar:2.13.0]
        at com.fasterxml.jackson.databind.deser.std.UntypedObjectDeserializer$Vanilla.deserialize(UntypedObjectDeserializer.java:707) ~[jackson-databind-2.13.0.jar:2.13.0]
        at com.fasterxml.jackson.databind.deser.std.UntypedObjectDeserializer$Vanilla.mapArray(UntypedObjectDeserializer.java:883) ~[jackson-databind-2.13.0.jar:2.13.0]
        at com.fasterxml.jackson.databind.deser.std.UntypedObjectDeserializer$Vanilla.deserialize(UntypedObjectDeserializer.java:721) ~[jackson-databind-2.13.0.jar:2.13.0]
        at com.fasterxml.jackson.databind.deser.std.UntypedObjectDeserializer$Vanilla.mapObject(UntypedObjectDeserializer.java:924) ~[jackson-databind-2.13.0.jar:2.13.0]
        at com.fasterxml.jackson.databind.deser.std.UntypedObjectDeserializer$Vanilla.deserialize(UntypedObjectDeserializer.java:707) ~[jackson-databind-2.13.0.jar:2.13.0]
        at com.fasterxml.jackson.databind.deser.std.UntypedObjectDeserializer$Vanilla.mapObject(UntypedObjectDeserializer.java:955) ~[jackson-databind-2.13.0.jar:2.13.0]
        at com.fasterxml.jackson.databind.deser.std.UntypedObjectDeserializer$Vanilla.deserialize(UntypedObjectDeserializer.java:707) ~[jackson-databind-2.13.0.jar:2.13.0]
        at com.fasterxml.jackson.databind.deser.std.UntypedObjectDeserializer$Vanilla.mapObject(UntypedObjectDeserializer.java:933) ~[jackson-databind-2.13.0.jar:2.13.0]
        at com.fasterxml.jackson.databind.deser.std.UntypedObjectDeserializer$Vanilla.deserialize(UntypedObjectDeserializer.java:707) ~[jackson-databind-2.13.0.jar:2.13.0]
        at com.fasterxml.jackson.databind.deser.std.UntypedObjectDeserializer$Vanilla.mapArray(UntypedObjectDeserializer.java:883) ~[jackson-databind-2.13.0.jar:2.13.0]
        at com.fasterxml.jackson.databind.deser.std.UntypedObjectDeserializer$Vanilla.deserialize(UntypedObjectDeserializer.java:721) ~[jackson-databind-2.13.0.jar:2.13.0]
        at com.fasterxml.jackson.databind.deser.std.MapDeserializer._readAndBindStringKeyMap(MapDeserializer.java:609) ~[jackson-databind-2.13.0.jar:2.13.0]
        at com.fasterxml.jackson.databind.deser.std.MapDeserializer.deserialize(MapDeserializer.java:437) ~[jackson-databind-2.13.0.jar:2.13.0]
        at com.fasterxml.jackson.databind.deser.std.MapDeserializer.deserialize(MapDeserializer.java:32) ~[jackson-databind-2.13.0.jar:2.13.0]
        at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:322) ~[jackson-databind-2.13.0.jar:2.13.0]
        at com.fasterxml.jackson.databind.ObjectMapper._readValue(ObjectMapper.java:4651) ~[jackson-databind-2.13.0.jar:2.13.0]
        at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2831) ~[jackson-databind-2.13.0.jar:2.13.0]
        at io.vertx.core.json.jackson.DatabindCodec.fromParser(DatabindCodec.java:126) ~[vertx-core-4.5.1.jar:4.5.1]
        at io.vertx.core.json.jackson.DatabindCodec.fromBuffer(DatabindCodec.java:99) ~[vertx-core-4.5.1.jar:4.5.1]
        at io.vertx.core.json.JsonObject.fromBuffer(JsonObject.java:1254) ~[vertx-core-4.5.1.jar:4.5.1]
        at io.vertx.core.json.JsonObject.<init>(JsonObject.java:85) ~[vertx-core-4.5.1.jar:4.5.1]
        at org.swisspush.gateleen.kafka.KafkaProducerRecordBuilder.lambda$buildRecordsAsync$1(KafkaProducerRecordBuilder.java:58) ~[gateleen-kafka-2.1.8.jar:?]
        at org.swisspush.gateleen.kafka.KafkaProducerRecordBuilder$$Lambda$3071/0x0000000840a94840.apply(Unknown Source) ~[?:?]
        at io.vertx.core.impl.future.Composition.onSuccess(Composition.java:38) ~[vertx-core-4.5.1.jar:4.5.1]
        at io.vertx.core.impl.future.FutureBase.emitSuccess(FutureBase.java:66) ~[vertx-core-4.5.1.jar:4.5.1]
        at io.vertx.core.impl.future.SucceededFuture.addListener(SucceededFuture.java:88) ~[vertx-core-4.5.1.jar:4.5.1]
        at io.vertx.core.impl.future.FutureBase.compose(FutureBase.java:90) ~[vertx-core-4.5.1.jar:4.5.1]
        at io.vertx.core.impl.future.SucceededFuture.compose(SucceededFuture.java:27) ~[vertx-core-4.5.1.jar:4.5.1]
        at io.vertx.core.Future.compose(Future.java:375) ~[vertx-core-4.5.1.jar:4.5.1]
        at org.swisspush.gateleen.kafka.KafkaProducerRecordBuilder.buildRecordsAsync(KafkaProducerRecordBuilder.java:55) ~[gateleen-kafka-2.1.8.jar:?]
        at org.swisspush.gateleen.kafka.KafkaHandler.lambda$handle$7(KafkaHandler.java:184) ~[gateleen-kafka-2.1.8.jar:?]
        at org.swisspush.gateleen.kafka.KafkaHandler$$Lambda$3070/0x0000000840a95440.handle(Unknown Source) ~[?:?]
        at io.vertx.core.impl.future.FutureImpl$1.onSuccess(FutureImpl.java:91) ~[vertx-core-4.5.1.jar:4.5.1]
        at io.vertx.core.impl.future.FutureBase.emitSuccess(FutureBase.java:66) ~[vertx-core-4.5.1.jar:4.5.1]
        at io.vertx.core.impl.future.FutureImpl.tryComplete(FutureImpl.java:246) ~[vertx-core-4.5.1.jar:4.5.1]
        at io.vertx.core.Promise.complete(Promise.java:66) ~[vertx-core-4.5.1.jar:4.5.1]
        at org.swisspush.gateleen.core.http.LocalHttpClientRequest$1$$Lambda$2622/0x00000008407cc040.handle(Unknown Source) ~[?:?]
        at org.swisspush.gateleen.core.http.BufferBridge.doEnd(BufferBridge.java:76) ~[gateleen-core-2.1.8.jar:?]
        at org.swisspush.gateleen.core.http.LocalHttpClientRequest.end(LocalHttpClientRequest.java:808) ~[gateleen-core-2.1.8.jar:?]
        at org.swisspush.gateleen.core.http.LocalHttpClientRequest.lambda$end$2(LocalHttpClientRequest.java:802) ~[gateleen-core-2.1.8.jar:?]
        at org.swisspush.gateleen.core.http.LocalHttpClientRequest$$Lambda$2623/0x00000008407cb840.handle(Unknown Source) ~[?:?]
        at io.vertx.core.impl.future.SucceededFuture.onComplete(SucceededFuture.java:81) ~[vertx-core-4.5.1.jar:4.5.1]
        at org.swisspush.gateleen.core.http.LocalHttpClientRequest.end(LocalHttpClientRequest.java:802) ~[gateleen-core-2.1.8.jar:?]
        at io.vertx.core.http.HttpClientRequest.send(HttpClientRequest.java:429) ~[vertx-core-4.5.1.jar:4.5.1]
        at org.swisspush.gateleen.queue.queuing.QueueProcessor.lambda$executeQueuedRequest$10(QueueProcessor.java:293) ~[gateleen-queue-2.1.8.jar:?]
        at org.swisspush.gateleen.queue.queuing.QueueProcessor$$Lambda$2618/0x00000008407d0440.handle(Unknown Source) ~[?:?]
        at io.vertx.core.impl.future.SucceededFuture.onComplete(SucceededFuture.java:81) ~[vertx-core-4.5.1.jar:4.5.1]
        at org.swisspush.gateleen.queue.queuing.QueueProcessor.executeQueuedRequest(QueueProcessor.java:240) ~[gateleen-queue-2.1.8.jar:?]
        at org.swisspush.gateleen.queue.queuing.QueueProcessor.lambda$startQueueProcessing$2(QueueProcessor.java:98) ~[gateleen-queue-2.1.8.jar:?]
        at org.swisspush.gateleen.queue.queuing.QueueProcessor$$Lambda$2540/0x0000000840984840.handle(Unknown Source) ~[?:?]
        at io.vertx.core.impl.ContextInternal.dispatch(ContextInternal.java:276) ~[vertx-core-4.5.1.jar:4.5.1]
        at io.vertx.core.eventbus.impl.MessageConsumerImpl.dispatch(MessageConsumerImpl.java:177) ~[vertx-core-4.5.1.jar:4.5.1]
        at io.vertx.core.eventbus.impl.HandlerRegistration$InboundDeliveryContext.execute(HandlerRegistration.java:137) ~[vertx-core-4.5.1.jar:4.5.1]
        at io.vertx.core.eventbus.impl.DeliveryContextBase.next(DeliveryContextBase.java:80) ~[vertx-core-4.5.1.jar:4.5.1]
        at io.vertx.core.eventbus.impl.DeliveryContextBase.dispatch(DeliveryContextBase.java:43) ~[vertx-core-4.5.1.jar:4.5.1]
        at io.vertx.core.eventbus.impl.HandlerRegistration.dispatch(HandlerRegistration.java:98) ~[vertx-core-4.5.1.jar:4.5.1]
        at io.vertx.core.eventbus.impl.MessageConsumerImpl.deliver(MessageConsumerImpl.java:183) ~[vertx-core-4.5.1.jar:4.5.1]
        at io.vertx.core.eventbus.impl.MessageConsumerImpl.doReceive(MessageConsumerImpl.java:168) ~[vertx-core-4.5.1.jar:4.5.1]
        at io.vertx.core.eventbus.impl.HandlerRegistration.lambda$receive$0(HandlerRegistration.java:49) ~[vertx-core-4.5.1.jar:4.5.1]
        at io.vertx.core.eventbus.impl.HandlerRegistration$$Lambda$1806/0x00000008407e9040.run(Unknown Source) ~[?:?]
        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:173) ~[netty-common-4.1.103.Final.jar:4.1.103.Final]
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:166) ~[netty-common-4.1.103.Final.jar:4.1.103.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) ~[netty-common-4.1.103.Final.jar:4.1.103.Final]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569) ~[netty-transport-4.1.103.Final.jar:4.1.103.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.103.Final.jar:4.1.103.Final]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.103.Final.jar:4.1.103.Final]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.103.Final.jar:4.1.103.Final]
        at java.lang.Thread.run(Thread.java:829) ~[?:?]
```

### PR DESCRIPTION
**Pull request by hiddenalpha**
Fixes #591

### CODE REVIEW

**Review by ljucam — APPROVED** [review]

File: gateleen-kafka/src/main/java/org/swisspush/gateleen/kafka/KafkaProducerRecordBuilder.java [hunk 1]
```diff
@@ -52,33 +52,31 @@ class KafkaProducerRecordBuilder {
...
     Future<List<KafkaProducerRecord<String, String>>> buildRecordsAsync(String topic, Buffer payload) {
-        return Future.<Void>succeededFuture().compose((Void v) -> {
+        return Future.<Void>succeededFuture().compose((Void v) -> vertx.executeBlocking(() -> {
+            long beginEpchMs = currentTimeMillis();
             JsonObject payloadObj;
             try {
                 payloadObj = new JsonObject(payload);
             } catch (DecodeException de) {
-                return Future.failedFuture(new ValidationException("Error while parsing payload", de));
+                throw new ValidationException("Error while parsing payload", de);
```
Comment (mcweba) [inline gateleen-kafka/src/main/java/org/swisspush/gateleen/kafka/KafkaProducerRecordBuilder.java:61]: Is the outcome really the same with returning a failed Future and throwing an Exception? I just found in vertx-rest-storage a place where we get an EventBus timeout when calling vertx-rest-storage from gateelen and there is an error in vertx-rest-storage. In this case, the EventBus message is not responded

**Review by mcweba — CHANGES_REQUESTED** [review]

File: gateleen-kafka/src/main/java/org/swisspush/gateleen/kafka/KafkaProducerRecordBuilder.java (hunk 1 above)
Comment (hiddenalpha) [reply gateleen-kafka/src/main/java/org/swisspush/gateleen/kafka/KafkaProducerRecordBuilder.java:61]: AFAIK its the way of how the newer "*executeBlocking*" works. But to be sure I will have a look how it actually behaves.

Comment (hiddenalpha) [reply gateleen-kafka/src/main/java/org/swisspush/gateleen/kafka/KafkaProducerRecordBuilder.java:61]: I did the following experiment which seems to support the thesis that the code is correct.
Reproducer:
```java
    public static void main(String[] args) {
        try {
            Vertx vertx = Vertx.vertx();
            Future<Object> fut = vertx.executeBlocking(() -> {
                throw new RuntimeException("hello exceptional world");
            });
            fut.onFailure(ex -> {
                System.out.println("Whopsee: "+ ex.getMessage());
            });
            fut.onSuccess(obj -> {
                System.out.println("It was ok :)");
            });
        } catch (Exception ex) {
            System.out.println("The outer catch block");
        }
    }
```
Result:
```
Whopsee: hello exceptional world
```
